import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Madhuri & Nirmal Wedding",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
        <head>
  <link rel="icon" href="./icons8-wedding-day-32.png" />
</head>
      <body
        className=""
      >
        {children}
      </body>
    </html>
  );
}
